name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.home.echoready.co.uk/jukebox-sonos:unstable
    - name: Push the docker image
      run: docker push registry.home.echoready.co.uk/jukebox-sonos:unstable
